[project]
name = "hover"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=9.0.2",
    "z3>=0.2.0",
]
[tool.pyright]
venvPath = "."
venv = ".venv"
reportAttributeAccessIssue = "none"
